# Numpy continue...

In [1]:
import numpy as np

In [4]:
def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1,2,3,4,5],[6,7,8,9,10]))

[7 9 11 13 15]


In [16]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([10, 20, 30, 40, 50, 60])

In [20]:
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[ 1  2  3  4  5  6 10 20 30 40 50 60]


In [25]:
arr1 = np.array([[1, 2, 3, 4, 5, 6], [12, 22, 32, 42, 52, 62]])
arr2 = np.array([[10, 20, 30, 40, 50, 60]])

In [27]:
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[[ 1  2  3  4  5  6]
 [12 22 32 42 52 62]
 [10 20 30 40 50 60]]


In [30]:
arr3 = np.concatenate((arr1, arr2), axis=None)
print(arr3)

[ 1  2  3  4  5  6 12 22 32 42 52 62 10 20 30 40 50 60]


In [36]:
arr2 = np.array([[43, 54]])
arr3 = np.concatenate((arr1, arr2.T), axis=1)
print(arr3)

[[ 1  2  3  4  5  6 43]
 [12 22 32 42 52 62 54]]


In [38]:
arr1 = np.array([[1, 2, 3, 4, 5, 6], [12, 22, 32, 42, 52, 62]])
arr2 = np.array([[10, 20, 30, 40, 50, 60]])
np.add(arr1,arr2)

array([[ 11,  22,  33,  44,  55,  66],
       [ 22,  42,  62,  82, 102, 122]])

In [41]:
np.subtract(arr2,arr1)

array([[ 9, 18, 27, 36, 45, 54],
       [-2, -2, -2, -2, -2, -2]])

In [42]:
np.multiply(arr1,arr2)

array([[  10,   40,   90,  160,  250,  360],
       [ 120,  440,  960, 1680, 2600, 3720]])

In [43]:
np.divide(arr1,arr2)

array([[0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       ],
       [1.2       , 1.1       , 1.06666667, 1.05      , 1.04      ,
        1.03333333]])

In [44]:
arr1 = np.array([[1, 2, 3, 4, 5, 6], [12, 22, 32, 42, 52, 62]])
arr2 = np.array([[1, 2, 3, 4, 5, 6]])
np.power(arr2,arr1)

array([[                   1,                    4,                   27,
                         256,                 3125,                46656],
       [                   1,              4194304,     1853020188851841,
                           0, -3394226340030730831,  4611686018427387904]])

In [47]:
arr1 = np.array([[1, 2, 3, 4, 5, 6], [12, 22, 32, 42, 52, 62]])
arr2 = np.array([[10, 20, 30, 40, 50, 60]])
print(np.mod(arr1,arr2))
print(np.remainder(arr1,arr2))

[[1 2 3 4 5 6]
 [2 2 2 2 2 2]]
[[1 2 3 4 5 6]
 [2 2 2 2 2 2]]


In [49]:
np.divmod(arr1,arr2)
# prints quotient and mod

(array([[0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1]]),
 array([[1, 2, 3, 4, 5, 6],
        [2, 2, 2, 2, 2, 2]]))

In [50]:
np.absolute(arr1)

array([[ 1,  2,  3,  4,  5,  6],
       [12, 22, 32, 42, 52, 62]])

In [52]:
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [53]:
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [54]:
arr = np.around(3.1666, 2)

print(arr)

3.17


In [56]:
arr = np.floor([-3.1666, 3.6667])
arr

array([-4.,  3.])

In [58]:
arr = np.ceil([-3.1666, 3.6667])
arr

array([-3.,  4.])

In [59]:
np.log(12)

2.4849066497880004

In [60]:
np.log2(12)

3.584962500721156

In [61]:
np.log10(12)

1.0791812460476249

In [67]:
from math import log
logarithm = np.frompyfunc(log,2,1)
print(logarithm(12,10))
print(logarithm(12,2))

1.0791812460476247
3.5849625007211565


In [68]:
arr1 = np.array([[1, 2, 3, 4, 5, 6], [12, 22, 32, 42, 52, 62]])
arr2 = np.sum(arr1)

In [69]:
arr2

243

In [70]:
arr3 = np.cumsum(arr1)
arr3

array([  1,   3,   6,  10,  15,  21,  33,  55,  87, 129, 181, 243])

In [72]:
arr4 = np.prod(arr1)
arr4

823627284480

In [74]:
arr5 = np.cumprod(arr1)
arr5

array([           1,            2,            6,           24,
                120,          720,         8640,       190080,
            6082560,    255467520,  13284311040, 823627284480])

In [75]:
np.diff(arr1)

array([[ 1,  1,  1,  1,  1],
       [10, 10, 10, 10, 10]])

In [83]:
np.lcm(8,6)

24

In [84]:
np.lcm.reduce([3,6,9])

18

In [77]:
np.gcd(14,80)

2

In [85]:
np.gcd.reduce([12,32,56])

4

In [88]:
x = np.sin(np.pi/2)
x

1.0

In [104]:
deg = np.array([0, 90, 180, 270, 360])

rad = np.deg2rad(deg)
rad

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [105]:
np.rad2deg(rad)

array([  0.,  90., 180., 270., 360.])

In [109]:
np.arcsin(1)

1.5707963267948966

In [110]:
np.hypot(3,4)

5.0

In [111]:
np.sinh(12)

81377.39570642984

In [112]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [116]:
arr1 = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
arr2 = np.array([11, 11, 11, 22, 33, 44, 55, 55, 66, 77])

np.union1d(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77])

In [119]:
arr1 = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
arr2 = np.array([1, 11, 11, 22, 33, 44, 55, 55, 66, 77])

np.intersect1d(arr1,arr2)

array([1])

In [120]:
np.setdiff1d(arr1,arr2)

array([2, 3, 4, 5, 6, 7])

In [121]:
np.setdiff1d(arr2,arr1)

array([11, 22, 33, 44, 55, 66, 77])

In [124]:
newarr = np.setxor1d(arr1, arr2, assume_unique=True)
# symmetric difference

In [125]:
newarr

array([ 2,  3,  4,  6,  7, 22, 33, 44, 66, 77])