# Numpy

In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arra = np.array((1,2,3,4,5,6))
arra

array([1, 2, 3, 4, 5, 6])

In [4]:
arr1 = np.array([[1,3,4],
                [12,141,122],
                [34,344,90], 
                 [12,23,56]])
arr1

array([[  1,   3,   4],
       [ 12, 141, 122],
       [ 34, 344,  90],
       [ 12,  23,  56]])

In [5]:
arr1 = np.array([[[1,3,4],[12,141,122]],
                 [[34,344,90], [12,23,56]]])
arr1

array([[[  1,   3,   4],
        [ 12, 141, 122]],

       [[ 34, 344,  90],
        [ 12,  23,  56]]])

In [6]:
arr1.ndim

3

In [7]:
print(arr1,"\n")
print(arr1[0],"\n")
print(arr1[0,0],"\n")

[[[  1   3   4]
  [ 12 141 122]]

 [[ 34 344  90]
  [ 12  23  56]]] 

[[  1   3   4]
 [ 12 141 122]] 

[1 3 4] 



In [8]:
arr2 = np.array([[1,3,4],[12,141,122],[34,344,90], [12,23,56]], ndmin=3)
arr2

array([[[  1,   3,   4],
        [ 12, 141, 122],
        [ 34, 344,  90],
        [ 12,  23,  56]]])

In [9]:
arr2.ndim

3

In [10]:
print(arr2[0],"\n")
print(arr2[0,0],"\n")
print(arr2[0,0,0],"\n")

[[  1   3   4]
 [ 12 141 122]
 [ 34 344  90]
 [ 12  23  56]] 

[1 3 4] 

1 



In [11]:
# slicing the array
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-4:])

[5 6 7 8]


In [12]:
arr[0:-1:3]
# (start:end:step)

array([1, 4, 7])

In [13]:
arr = np.array([[1,2,3,4,5,6,7,8],
              [11,12,13,14,15,61,71,81]])
print(arr[0, 1:4])
print(arr[1, 1:4])
# arr[index, start:end]

[2 3 4]
[12 13 14]


In [14]:
arr = np.array([[1,2,3,4,5,6,7,8],
              [11,12,13,14,15,61,71,81]])
print(arr[0:2, 2])
print(arr[1:4, 3])
# arr[start:end, index] , index after slicing

[ 3 13]
[14]


In [15]:
print(arr.dtype)

int64


In [7]:
arr = np.array([1,2,3,5,6], dtype='S')
print(arr.dtype)
print(arr)

|S1
[b'1' b'2' b'3' b'5' b'6']


<pre>
below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
</pre>

In [17]:
new_arr = arr.astype('i')
print(new_arr.dtype)
print(new_arr)

int32
[1 2 3 5 6]


In [18]:
arr = np.array([0, 2, 3, 4], dtype='i4')
print(arr.dtype)

int32


In [19]:
new_arr = arr.astype('bool')
print(new_arr.dtype)
print(new_arr)

bool
[False  True  True  True]


In [20]:
new1 = arr.copy()
print(new1)

[0 2 3 4]


In [21]:
view1 = arr.view()
print(view1)

[0 2 3 4]


In [22]:
# now changing data in arr1 let's see what happens in view1 and new1
arr[0]=122
print(new1)
print(view1)

[0 2 3 4]
[122   2   3   4]


<pre>
Here we can observe that after changing in arr new1 is as it is but view1 also changed.

This is because new1 is a new array and copied from arr and now owns the data
While view1 is not an array it views the arr array and show the data arr owns
</pre>

In [23]:
# check if the data is it's own or not using base

print(new1.base)
print(view1.base)
# new1 prints none because it has it's own value while view1 prints value from arr

None
[122   2   3   4]


In [24]:
arr.shape

(4,)

In [25]:
# arr = arr.reshape(1,8)
# print(arr)

In [26]:
# arr = arr.reshape(2,2,2)
# print(arr)

In [27]:
view1

array([122,   2,   3,   4], dtype=int32)

In [28]:
v1 = view1.reshape(1,2,2).base

In [29]:
print(v1)

[122   2   3   4]


In [30]:
arr = arr.reshape(-1)
print(arr)

[122   2   3   4]


In [31]:
arr.shape

(4,)

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9


In [15]:
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6
7
9


In [16]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

In [38]:
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
arr4 = np.stack((arr1,arr2), axis=1)
print(arr4)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [40]:
arr5 = np.hstack((arr1,arr2))
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
arr6 = np.vstack((arr1,arr2))
print(arr6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [42]:
arr6 = np.dstack((arr1,arr2))
print(arr6)

[[[ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]
  [ 6 12]]]


In [62]:
arra = np.array([1,2,3,4,5,6,7,8,8,9,9,9,12,34,21,1212])
arr7 = np.array_split(arra, 9)
print(arr7)
# arra split into 9 different array

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([8, 9]), array([9, 9]), array([12, 34]), array([21]), array([1212])]


In [44]:
arra = np.array([[1,2,3,4],[5,6,7,8],[8,9,9,9],[12,34,21,1212]])
arr7 = np.array_split(arra, 3, axis=1)
print(arr7)
# arra split into 9 different array horizontally

[array([[ 1,  2],
       [ 5,  6],
       [ 8,  9],
       [12, 34]]), array([[ 3],
       [ 7],
       [ 9],
       [21]]), array([[   4],
       [   8],
       [   9],
       [1212]])]


In [45]:
arra = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
arr7 = np.hsplit(arra, 3)
print(arr7)
# arra split into 9 different array horizontally

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [46]:
arra = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
arr7 = np.vsplit(arra, 3)
print(arr7)
# arra split into 9 different array vertically

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [58]:
arra = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
aee = np.where(arra > 6)
print(aee)
# the array it prints give the position of the array not value

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),)


In [59]:
print(np.searchsorted(arra, 9))

8


In [60]:
print(np.searchsorted(arra, 9, side='right'))

9


In [61]:
print(np.searchsorted(arra, [1,2,3]))

[0 1 2]


In [64]:
print(np.sort(arra))

[   1    2    3    4    5    6    7    8    8    9    9    9   12   21
   34 1212]


In [65]:
# filtering 

arr10 = np.array([1, 4, 6, 7])
a_x = [True, False, False, False]

print(arr10[a_x])

[1]


In [72]:
# filtering 

arr10 = np.array([1, 41, 16, 71, 54, 67, 22, 90])
arr10 = np.sort(arr10)
a_x = []
for i in arr10:
    if i > 45:
        a_x.append(True)
    else:
        a_x.append(False)

print(np.sort(arr10[a_x]))

[54 67 71 90]
